# Usar imagem base do Python
FROM python:3.13-slim

# Definir diretório de trabalho
WORKDIR /app

# Copiar requirements.txt e instalar dependências
COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

# Copiar apenas os arquivos necessários para a API
COPY api/ ./api/

# Expor porta da API
EXPOSE 8000

# Comando para iniciar a API
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
