services:
  api:
    image: fernandodumont/fiap-fase-1-api:1.0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_FILE=/app/data/books.csv
    networks:
      - app-network

  dashboard:
    image: fernandodumont/fiap-fase-1-dashboard:1.0
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - API_HOST=http://api:8000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
